spring.application.name=CartService
server.port=8081

# MongoDB (Docker)
spring.data.mongodb.uri=mongodb://localhost:27017/cart_service
spring.data.mongodb.auto-index-creation=true

# Redis (Docker)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Other services
services.auth.url=http://localhost:9000
services.product.url=http://localhost:8080
